repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [--fix]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.411
    hooks:
      - id: pyright
