"""drop static gtfs fks and audit columns

Revision ID: e54dc32d1b96
Revises: 9161a426452a
Create Date: 2026-09-04 00:33:58.214460

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e54dc32d1b96"
down_revision: str | None = "9161a426452a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agency", "created_at")
    op.drop_column("agency", "updated_at")
    op.drop_column("calendar", "created_at")
    op.drop_column("calendar", "updated_at")
    op.drop_constraint(op.f("fk_calendar_date_service_id_calendar"), "calendar_date", type_="foreignkey")
    op.drop_column("calendar_date", "created_at")
    op.drop_column("calendar_date", "updated_at")
    op.drop_constraint(op.f("fk_route_agency_id_agency"), "route", type_="foreignkey")
    op.drop_column("route", "created_at")
    op.drop_column("route", "updated_at")
    op.drop_column("shape", "created_at")
    op.drop_column("shape", "updated_at")
    op.drop_constraint(op.f("fk_stop_parent_station_stop"), "stop", type_="foreignkey")
    op.drop_column("stop", "created_at")
    op.drop_column("stop", "updated_at")
    op.drop_constraint(op.f("fk_stop_time_stop_id_stop"), "stop_time", type_="foreignkey")
    op.drop_constraint(op.f("fk_stop_time_trip_id_trip"), "stop_time", type_="foreignkey")
    op.drop_column("stop_time", "created_at")
    op.drop_column("stop_time", "updated_at")
    op.drop_constraint(op.f("fk_trip_route_id_route"), "trip", type_="foreignkey")
    op.drop_constraint(op.f("fk_trip_service_id_calendar"), "trip", type_="foreignkey")
    op.drop_column("trip", "created_at")
    op.drop_column("trip", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trip",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "trip",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_trip_service_id_calendar"), "trip", "calendar", ["service_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        op.f("fk_trip_route_id_route"), "trip", "route", ["route_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "stop_time",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "stop_time",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_stop_time_trip_id_trip"), "stop_time", "trip", ["trip_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(op.f("fk_stop_time_stop_id_stop"), "stop_time", "stop", ["stop_id"], ["id"])
    op.add_column(
        "stop",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "stop",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(op.f("fk_stop_parent_station_stop"), "stop", "stop", ["parent_station"], ["id"])
    op.add_column(
        "shape",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "shape",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "route",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "route",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_route_agency_id_agency"), "route", "agency", ["agency_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "calendar_date",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "calendar_date",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_calendar_date_service_id_calendar"),
        "calendar_date",
        "calendar",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "calendar",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "calendar",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "agency",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "agency",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
