"""drop rt fks and updated_at

Revision ID: f4f044140520
Revises: e54dc32d1b96
Create Date: 2026-09-04 01:27:02.665895

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4f044140520"
down_revision: str | None = "e54dc32d1b96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rt_stop_time_entity_id"), table_name="rt_stop_time")
    op.drop_constraint(op.f("fk_rt_stop_time_trip_id_trip"), "rt_stop_time", type_="foreignkey")
    op.drop_constraint(op.f("fk_rt_stop_time_stop_id_stop"), "rt_stop_time", type_="foreignkey")
    op.drop_column("rt_stop_time", "updated_at")
    op.drop_index(op.f("ix_rt_trip_entity_id"), table_name="rt_trip")
    op.drop_constraint(op.f("fk_rt_trip_trip_id_trip"), "rt_trip", type_="foreignkey")
    op.drop_constraint(op.f("fk_rt_trip_route_id_route"), "rt_trip", type_="foreignkey")
    op.drop_column("rt_trip", "updated_at")
    op.drop_constraint(op.f("fk_rt_vehicle_trip_id_trip"), "rt_vehicle", type_="foreignkey")
    op.drop_column("rt_vehicle", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rt_vehicle",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_rt_vehicle_trip_id_trip"), "rt_vehicle", "trip", ["trip_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "rt_trip",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_rt_trip_route_id_route"), "rt_trip", "route", ["route_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        op.f("fk_rt_trip_trip_id_trip"), "rt_trip", "trip", ["trip_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(op.f("ix_rt_trip_entity_id"), "rt_trip", ["entity_id"], unique=False)
    op.add_column(
        "rt_stop_time",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_rt_stop_time_stop_id_stop"), "rt_stop_time", "stop", ["stop_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        op.f("fk_rt_stop_time_trip_id_trip"), "rt_stop_time", "trip", ["trip_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(op.f("ix_rt_stop_time_entity_id"), "rt_stop_time", ["entity_id"], unique=False)
    # ### end Alembic commands ###
