name: Tests on Pull Request

on:
  pull_request:
    branches: ["*"]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: TEST
      GTFS_TFI_DATASET: TFI

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.14.3"
          activate-environment: true

      - name: Install dependencies
        run: uv pip install -r requirements-top-level.txt

      - name: Install dev dependencies
        run: uv pip install -r requirements-dev.txt

      - name: Run tests with coverage
        run: coverage run --branch -m pytest

      - name: Print coverage summary
        if: ${{ !cancelled() }}
        run: coverage report

      - name: Create HTML coverage report
        if: ${{ !cancelled() }}
        run: coverage html --show-contexts

      - name: Upload coverage report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: htmlcov/
